### ISSUE TITLE
downloading error

### ISSUE THREAD

**Issue by JloveL** [cchyung/freesound-scraper#1]
Traceback (most recent call last):
  File "freesounds_scraper.py", line 173, in <module>
    main(args)
  File "freesounds_scraper.py", line 143, in main
    download(data, download_location)
  File "freesounds_scraper.py", line 109, in download
    data.remove_unsuccessful(unsuccessful_downloads)
  File "/home/atticus/PycharmProjects/freesound-scraper/data.py", line 63, in remove_unsuccessful
    self.data_array = np.delete(self.data_array, unsuccessful, axis=0)
  File "/home/atticus/anaconda3/lib/python3.6/site-packages/numpy/lib/function_base.py", line 4397, in delete
    obj = obj.astype(intp)
ValueError: invalid literal for int() with base 10: '145788.wav'

**Comment by JloveL** [comment]
not a problem...

**Comment by ptanmay143** [comment]
Hi @DengJinCS. How did you solve this issue? I am facing the same error.
